---
- name: Create application namespace if does not exist
  ansible.builtin.command: "kubectl create ns {{ application_namespace }}"
  when: application_namespace not in namespaces.stdout.split()
  changed_when: application_namespace not in namespaces.stdout.split()

- name: Create argocd namespace if does not exist
  ansible.builtin.command: "kubectl create ns {{ argocd_namespace }}"
  when: argocd_namespace not in namespaces.stdout.split()
  changed_when: argocd_namespace not in namespaces.stdout.split()

- name: Create gitlab namespace if does not exist
  ansible.builtin.command: "kubectl create ns {{ gitlab_namespace }}"
  when: gitlab_namespace not in namespaces.stdout.split()
  changed_when: gitlab_namespace not in namespaces.stdout.split()
