---
- name: "Get all secrets in {{ secrets_namespace }} namespace"
  ansible.builtin.command: "kubectl get secrets -n {{ secrets_namespace }} -o jsonpath='{.items[*].metadata.name}'"
  register: secrets
  changed_when: false
