Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "ssabbajiS" do |server|
    server.vm.hostname = "ssabbajiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/setup.sh"
    server.vm.synced_folder "./confs", "/home/vagrant/confs", create: true
  end
end
