Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "ssabbajiS" do |server|
    server.vm.hostname = "ssabbajiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.name = "ssabbajiS-p2"
      v.memory = 2048
      v.cpus = 1
    end
    server.vm.provider "libvirt" do |lv|
      lv.driver = "qemu"
      lv.cpu_mode = "custom"
      lv.cpu_model = "qemu64"
      lv.memory = 2048
      lv.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/setup.sh"
  end
end
