---
- name: Add Argo Helm repo
  ansible.builtin.command: helm repo add argo https://argoproj.github.io/argo-helm

- name: Install ArgoCD Helm Chart
  ansible.builtin.command: helm upgrade --install argocd argo/argo-cd -n argocd --wait --timeout 0s

- name: Disable ArgoCD TLS
  ansible.builtin.command: "kubectl patch cm argocd-cmd-params-cm -n argocd -p '{\"data\": {\"server.insecure\": \"true\"}}'"

- name: Restart argocd-server
  ansible.builtin.command: kubectl rollout restart deploy argocd-server -n argocd

- name: Wait for argocd-server to be available
  ansible.builtin.command: kubectl wait --for=condition=Available deploy/argocd-server -n argocd

- name: Copy ArgoCD Application manifest
  ansible.builtin.template:
    src: templates/application.yaml.j2
    dest: "{{ base_dir }}/application.yaml"
  tags:
    - copy-argocd-app-file

- name: Create ArgoCD Application
  ansible.builtin.command: "kubectl apply -f {{ base_dir }}/application.yaml"
  tags:
    - create-argocd-app
