Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "ssabbajiS" do |server|
    server.vm.hostname = "ssabbajiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.name = "ssabbajiS"
      v.memory = 2048
      v.cpus = 1
    end
    server.vm.provider "libvirt" do |lv|
      lv.driver = "qemu"
      lv.cpu_mode = "custom"
      lv.cpu_model = "qemu64"
      lv.memory = 1024
      lv.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "ssabbajiSW" do |worker|
    worker.vm.hostname = "ssabbajiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.name = "ssabbajiSW"
      v.memory = 1024
      v.cpus = 1
    end
    worker.vm.provider "libvirt" do |lv|
      lv.driver = "qemu"
      lv.cpu_mode = "custom"
      lv.cpu_model = "qemu64"
      lv.memory = 1024
      lv.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
