Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "ssabbajiS" do |server|
    server.vm.hostname = "ssabbajiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "vmware_desktop" do |v|
    #  v.name = "ssabbajiS"
      v.memory = 2048
      v.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "ssabbajiSW" do |worker|
    worker.vm.hostname = "ssabbajiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "vmware_desktop" do |v|
    #  v.name = "ssabbajiSW"
      v.memory = 1024
      v.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
