---
- name: Install k3d
  ansible.builtin.shell: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
  become: true

- name: Copy configuration file
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: "{{ base_dir }}/k3d-config.yaml"

- name: Get current clusters
  ansible.builtin.shell: k3d cluster list -o json | jq -r '.[].name'
  register: clusters
  changed_when: false

- name: Create cluster if does not exist
  ansible.builtin.command: "k3d cluster create --config {{ base_dir }}/k3d-config.yaml"
  when: cluster_name not in clusters.stdout.split('\n')

- name: Get helm install trefik job
  ansible.builtin.command: "kubectl get job --selector helmcharts.helm.cattle.io/chart=traefik -n kube-system -o jsonpath='{.items[0].metadata.name}'"
  register: helm_install_traefik_job
  changed_when: false

- name: Get helm install traefik crd job
  ansible.builtin.command: "kubectl get job --selector helmcharts.helm.cattle.io/chart=traefik-crd -n kube-system -o jsonpath='{.items[0].metadata.name}'"
  register: helm_install_traefik_crd_job
  changed_when: false

- name: Wait for helm install traefik job to complete
  ansible.builtin.command: "kubectl wait --for=condition=complete -n kube-system job/{{ helm_install_traefik_job.stdout }} --timeout 5m"
  changed_when: false

- name: Wait for helm install traefik crd job to complete
  ansible.builtin.command: "kubectl wait --for=condition=complete -n kube-system job/{{ helm_install_traefik_crd_job.stdout }} --timeout 5m"
  changed_when: false
