Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.ssh.insert_key = false

  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "vmware_desktop" do |v|
    v.memory = 16284
    v.cpus = 8
  end
end
