Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.ssh.insert_key = false

  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.network "forwarded_port", host: 80, guest: 80
end
