---
- ansible.builtin.import_tasks:
    file: tasks/get_secrets.yaml
  vars:
    secrets_namespace: "{{ gitlab_namespace }}"

- name: Create Secret holding PostgreSQL password
  ansible.builtin.command: "kubectl create secret generic {{ psql_secret_name }} --from-literal=password={{ psql_password }} --from-literal=admin-password={{ psql_admin_password }} -n {{ gitlab_namespace }}"
  when: psql_secret_name not in secrets.stdout.split()

- name: Copy values file of PostgreSQL Helm Chart
  ansible.builtin.template:
    src: templates/values.yaml.j2
    dest: "{{ values_dir }}/postgres-values.yaml"

- name: Install PostgreSQL Helm Chart
  ansible.builtin.command: "helm upgrade --install {{ psql_release_name }} oci://registry-1.docker.io/bitnamicharts/postgresql --values {{ values_dir }}/postgres-values.yaml -n {{ gitlab_namespace }} --wait --timeout 1h"
