---
- name: Copy values file of Minio Helm Chart
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: templates/values.yaml.j2
      dest: "{{ values_dir }}/minio-values.yaml"

- ansible.builtin.import_tasks:
    file: tasks/get_secrets.yaml
  vars:
    secrets_namespace: "{{ gitlab_namespace }}"

- name: Create Secret holding access and secret keys
  ansible.builtin.command: "kubectl create secret generic {{ minio_secret_name }} -n {{ gitlab_namespace }} --from-literal=accessKey={{ minio_access_key }} --from-literal=secretKey={{ minio_secret_access_key }}"
  when: minio_secret_name not in secrets.stdout.split()

- name: Add Bitnami Helm Chart
  ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami
  when: "'bitnami' not in helm_repos.stdout.split('\n')"

- name: Install Minio Helm Chart
  ansible.builtin.command: "helm upgrade --install {{ minio_release_name }} bitnami/minio --values {{ values_dir }}/minio-values.yaml -n {{ gitlab_namespace }} --wait --timeout 1h"
