---
- name: Remove conflicting packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker.io
    - docker-doc
    - docker-buildx
    - podman-docker
    - containerd
    - runc

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - python3-debian

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "a+r"

- name: Get architecture
  ansible.builtin.command: dpkg --print-architecture
  register: arch
  changed_when: false

- name: Add docker repository
  ansible.builtin.deb822_repository:
    name: docker-ce
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    architectures: "{{ arch.stdout }}"
    signed_by: /etc/apt/keyrings/docker.asc

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin

- name: Update apt cache
  ansible.builtin.apt: update_cache=true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add current to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker

- name: Reset connection to apply group membership
  ansible.builtin.meta: reset_connection
