---
- name: Copy connection and values files of Gitlab Helm Chart
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: templates/values.yaml.j2
      dest: "{{ values_dir }}/gitlab-values.yaml"
    - src: templates/rails.yaml.j2
      dest: "{{ base_dir }}/minio-rails.yaml"
  tags:
    - copy-gitlab-values-file
    - install-gitlab

- ansible.builtin.import_tasks:
    file: tasks/get_secrets.yaml
  vars:
    secrets_namespace: "{{ gitlab_namespace }}"

- name: Create Secret holding connection yaml file
  ansible.builtin.command: "kubectl create secret generic {{ connection_secret_name }} --from-file=connection={{ base_dir }}/minio-rails.yaml -n {{ gitlab_namespace }}"
  when: connection_secret_name not in secrets.stdout.split()

- name: Add Gitlab Helm repo
  ansible.builtin.command: helm repo add gitlab https://charts.gitlab.io/
  tags:
    - install-gitlab

- name: Update Helm repo
  ansible.builtin.command: helm repo update
  changed_when: false
  tags:
    - install-gitlab

- name: "Install Gitlab version {{ gitlab_helm_chart_version }}"
  ansible.builtin.command: "helm upgrade --install {{ gitlab_release_name }} gitlab/gitlab --version {{ gitlab_helm_chart_version }} --values {{ values_dir }}/gitlab-values.yaml -n {{ gitlab_namespace }} --wait --timeout 1h"
  tags:
    - install-gitlab
